# Generated by Django 4.1.4 on 2022-12-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_alter_cocktail_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ing_type', models.CharField(choices=[('Alc', 'Alcohol'), ('Sof', 'Soft-drinks'), ('Gar', 'Garnish'), ('Oth', 'Other')], default='Oth', max_length=11)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('inv_type', models.CharField(choices=[('tableware', 'Tableware'), ('instrument', 'Instrument'), ('other', 'Other')], max_length=10)),
            ],
        ),
    ]
