# Generated by Django 4.1.4 on 2022-12-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0004_ingredients_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='main_ingredients',
            field=models.ManyToManyField(to='drinks.ingredients'),
        ),
    ]
