# Generated by Django 4.1.4 on 2022-12-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0005_cocktail_main_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='optional_ingredients',
            field=models.ManyToManyField(related_name='optional_ingredients', to='drinks.ingredients'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='main_ingredients',
            field=models.ManyToManyField(related_name='main_ingredients', to='drinks.ingredients'),
        ),
    ]
