# Generated by Django 4.1.4 on 2022-12-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0006_cocktail_optional_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='tools',
            field=models.ManyToManyField(related_name='tools', to='drinks.inventory'),
        ),
    ]
