# Generated by Django 4.1.4 on 2023-01-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0008_cocktail_recepie_alter_cocktail_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='image',
            field=models.ImageField(null=True, upload_to='cocktails_images'),
        ),
    ]
