# Generated by Django 4.1.4 on 2023-01-05 07:58

from django.db import migrations, models
import drinks.models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0010_alter_cocktail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=drinks.models.path_and_rename),
        ),
    ]
