# Generated by Django 4.1.4 on 2023-01-19 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drinks', '0012_alter_cocktail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinks.ingredients')),
                ('user_tools', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinks.inventory')),
            ],
        ),
    ]
