# Generated by Django 4.1.4 on 2023-01-24 15:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drinks', '0014_remove_userstorage_user_tools'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userstorage',
            unique_together={('user_id', 'user_ingredients')},
        ),
    ]
