# Generated by Django 4.1.4 on 2023-01-25 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drinks', '0015_alter_userstorage_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinks.inventory')),
            ],
            options={
                'unique_together': {('user', 'user_inventory')},
            },
        ),
    ]
