# Generated by Django 4.2.5 on 2023-09-25 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drinks', '0016_usertools'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, auto_now=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
