# Generated by Django 4.1.4 on 2023-01-25 15:43

from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default/default-cooktail-user.png', upload_to=forum.models.CustomUser.image_upload_to),
        ),
    ]
